# Generated by Django 2.2.9 on 2020-01-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fec_fundacion', models.DateField()),
                ('estilo', models.CharField(choices=[('indie', 'indie'), ('pop', 'pop'), ('rock', 'rock')], default='pop', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fec_nacimiento', models.DateField()),
                ('instrumento', models.CharField(choices=[('voz', 'voz'), ('piano', 'piano'), ('bajo', 'bajo'), ('bateria', 'bateria'), ('guitarra', 'guitarra')], default='voz', max_length=30)),
                ('grupos', models.ManyToManyField(to='práctica_05.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(to='práctica_05.Musico'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('distribuidora', models.CharField(max_length=50)),
                ('fec_lanzamiento', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='práctica_05.Grupo')),
            ],
        ),
    ]
