# Generated by Django 2.2.8 on 2019-12-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fec_fundacion', models.DateField()),
                ('estilo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fec_nacimiento', models.DateField()),
                ('instrumento', models.CharField(blank=True, max_length=20)),
                ('grupos', models.ManyToManyField(to='práctica_05.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(to='práctica_05.Musico'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('distribuidora', models.CharField(max_length=50)),
                ('fec_lanzamiento', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='práctica_05.Grupo')),
            ],
        ),
    ]
