# Generated by Django 2.2.9 on 2020-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('práctica_05', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='práctica_05.Grupo'),
        ),
    ]
